version: "3.5"
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=banco123
      - POSTGRES_DB=parking-control-db
    ports:
      - "5432:5432"
    restart: unless-stopped